interval: # Delays, used in HTTP (in seconds)
  update: 3600
  next_attempt: 60


#send_by:  # One method must be selected at the same time
#  http: true
#  websocket: false
timeout: 30


get_node: # for GET requests
  primary: # Main server for GET requests:
    host: 127.0.0.1
    port: 8080
    login: gateway
    password: gateway
  mirror: # Mirror of main server for GET requests:
    host: 127.0.0.1
    port: 8080
    login: gateway 
    password: gateway


# By default, the gateway will not send post requests to the GET server.
# If you need to send POST requests to the receiving server,
# you need to explicitly write that here.
post:
  - node1:
      primary: # Main server for POST requests:
        host: 127.0.0.1
        port: 8080
        login: gateway
        password: gateway
      mirror: # Mirror of main server for GET requests:
        host: 127.0.0.1
        port: 8080
        login: gateway
        password: gateway
