RESET MASTER;

SET GLOBAL max_connections=1000;
SET GLOBAL gtid_strict_mode=ON;

CHANGE MASTER TO MASTER_HOST='master', MASTER_PORT=3306, MASTER_USER='master', MASTER_PASSWORD='masterpa$$', MASTER_USE_GTID=slave_pos, MASTER_LOG_POS=4, MASTER_LOG_FILE='mariadb-bin.000001', MASTER_CONNECT_RETRY=1;;
START SLAVE;

