RESET MASTER;

SET GLOBAL max_connections=1000;
SET GLOBAL gtid_strict_mode=ON;

CHANGE MASTER TO MASTER_HOST='master', MASTER_PORT=3306, MASTER_USER='visiobas', MASTER_PASSWORD='locpa$$', MASTER_USE_GTID=slave_pos;
START SLAVE;

